### ISSUE TITLE
Gtk# 2.12 branch: fixing mono compilation errors

### ISSUE THREAD

**Issue by plprevost** [mono/gtk-sharp#298]
Some erros are to be fixed when trying to compile with mono 6.0.12.107

Example:
make[2]: Entering directory '/builds/organization/project/component/gtk-sharp/sample/test'
/usr/bin/mcs -out:WidgetViewer.exe -r:../../glib/glib-sharp.dll -r:../../pango/pango-sharp.dll -r:../../atk/atk-sharp.dll -r:../../gdk/gdk-sharp.dll -r:../../gtk/gtk-sharp.dll ./TestCheckButton.cs ./TestColorSelection.cs ./TestRadioButton.cs ./TestRange.cs ./TestStatusbar.cs ./TestDialog.cs ./TestFlipping.cs ./TestSizeGroup.cs ./TestCombo.cs ./TestComboBox.cs ./WidgetViewer.cs
./TestCombo.cs(17,14): warning CS0612: `Gtk.Combo' is obsolete
./TestRange.cs(35,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
/builds/organization/project/component/gtk-sharp/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
./TestRange.cs(35,13): error CS0030: Cannot convert type `Gtk.HScale' to `System.Range'
./TestRange.cs(42,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
/builds/organization/project/component/gtk-sharp/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
./TestRange.cs(42,13): error CS0030: Cannot convert type `Gtk.HScrollbar' to `System.Range'
./TestRange.cs(62,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
/builds/organization/project/component/gtk-sharp/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
./TestRange.cs(62,13): error CS0030: Cannot convert type `Gtk.VScale' to `System.Range'
./TestCombo.cs(31,20): warning CS0612: `Gtk.Combo' is obsolete
Compilation failed: 6 error(s), 2 warnings
make[2]: Leaving directory '/builds/organization/project/component/gtk-sharp/sample/test'
make[2]: *** [Makefile:505: WidgetViewer.exe] Error 1
make[1]: *** [Makefile:440: install-recursive] Error 1
make[1]: Leaving directory '/builds/organization/project/component/gtk-sharp/sample'
make: *** [Makefile:454: install-recursive] Error 1
