### ISSUE TITLE
Fails to build with Mono 6.4.0 `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'

### ISSUE THREAD

**Issue by Mailaender** [mono/gtk-sharp#282]
```
[  154s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41/sample/test'
[  154s] /usr/bin/mcs -out:WidgetViewer.exe -r:../../glib/glib-sharp.dll -r:../../pango/pango-sharp.dll -r:../../atk/atk-sharp.dll -r:../../gdk/gdk-sharp.dll -r:../../gtk/gtk-sharp.dll ./TestCheckButton.cs ./TestColorSelection.cs ./TestRadioButton.cs ./TestRange.cs ./TestStatusbar.cs ./TestDialog.cs ./TestFlipping.cs ./TestSizeGroup.cs ./TestCombo.cs ./TestComboBox.cs ./WidgetViewer.cs
[  154s] ./TestCombo.cs(17,14): warning CS0612: `Gtk.Combo' is obsolete
[  154s] ./TestRange.cs(35,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
[  154s] /usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
[  154s] /home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
[  154s] ./TestRange.cs(35,13): error CS0030: Cannot convert type `Gtk.HScale' to `System.Range'
[  154s] ./TestRange.cs(42,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
[  154s] /usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
[  154s] /home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
[  154s] ./TestRange.cs(42,13): error CS0030: Cannot convert type `Gtk.HScrollbar' to `System.Range'
[  154s] ./TestRange.cs(62,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
[  154s] /usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
[  154s] /home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
[  154s] ./TestRange.cs(62,13): error CS0030: Cannot convert type `Gtk.VScale' to `System.Range'
[  154s] ./TestCombo.cs(31,20): warning CS0612: `Gtk.Combo' is obsolete
[  154s] Compilation failed: 6 error(s), 2 warnings
[  154s] make[3]: *** [Makefile:504: WidgetViewer.exe] Error 1
[  154s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41/sample/test'
[  154s] make[2]: *** [Makefile:439: all-recursive] Error 1
[  154s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41/sample'
[  154s] make[1]: *** [Makefile:453: all-recursive] Error 1
[  154s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/gtk-sharp-2.12.41'
[  154s] make: *** [Makefile:381: all] Error 2
[  154s] error: Bad exit status from /var/tmp/rpm-tmp.BlzUbN (%build)
```

**Comment by DimStar77** [comment]
https://github.com/mono/gtk-sharp/commit/3faabd7bdce8f3e3e59f0ee945f4f36ea6d3e870.patch

has been fixed about a year ago

**Comment by Mailaender** [comment]
I see. https://build.opensuse.org/request/show/768336
